<a href="https://colab.research.google.com/github/MiorLear/Learning-Log/blob/main/Aprendiendo_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Intro to Machine Learning (By Kaggle)

In [ ]:
import kagglehub
import pandas as pd

In [ ]:
#Importando Melbourne Dataset
path = kagglehub.dataset_download("dansbecker/melbourne-housing-snapshot")
path = path + "/melb_data.csv"
melbourne_data = pd.read_csv(path)

Using Colab cache for faster access to the 'melbourne-housing-snapshot' dataset.

In [ ]:
melbourne_data.describe()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,13580.000000,1.358000e+04,13580.000000,13580.000000,13580.000000,13580.000000,13518.000000,13580.000000,7130.000000,8205.000000,13580.000000,13580.000000,13580.000000
mean,2.937997,1.075684e+06,10.137776,3105.301915,2.914728,1.534242,1.610075,558.416127,151.967650,1964.684217,-37.809203,144.995216,7454.417378
std,0.955748,6.393107e+05,5.868725,90.676964,0.965921,0.691712,0.962634,3990.669241,541.014538,37.273762,0.079260,0.103916,4378.581772
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,-38.182550,144.431810,249.000000
25%,2.000000,6.500000e+05,6.100000,3044.000000,2.000000,1.000000,1.000000,177.000000,93.000000,1940.000000,-37.856822,144.929600,4380.000000
50%,3.000000,9.030000e+05,9.200000,3084.000000,3.000000,1.000000,2.000000,440.000000,126.000000,1970.000000,-37.802355,145.000100,6555.000000
75%,3.000000,1.330000e+06,13.000000,3148.000000,3.000000,2.000000,2.000000,651.000000,174.000000,1999.000000,-37.756400,145.058305,10331.000000
max,10.000000,9.000000e+06,48.100000,3977.000000,20.000000,8.000000,10.000000,433014.000000,44515.000000,2018.000000,-37.408530,145.526350,21650.000000

### Preguntas
**Esta desviación estandar es poblacional o muestral?**

---

Es muestral, pandas por defecto considera grados de libertad n-1, si se quiere la desviación poblacional se tiene que especificar del siguiente modo:

In [ ]:
#Desviación estandar poblacional
stdp =melbourne_data["Price"].std(ddof=0)
print("std poblacional:",stdp)
#Desviación estandar muestral
stdma = melbourne_data["Price"].std(ddof=1)
stdmb = melbourne_data["Price"].std()
if stdma == stdmb:
  print("ambos metodos dan la misma std muestral:", stdma,  stdma == stdmb)

std poblacional: 639287.1851762081
ambos metodos dan la misma std muestral: 639310.7242960194 True

**cómo interpreto los cuartiles (quartesrs)**

---
*"Es la cantidad de información correspondiente a una columna que cae en dicho porcentaje"*

Osea, por ejemplo en la tabla de arriba, la columna rooms:

In [ ]:
melbourne_data.Rooms.quantile([0, .25, .5, .75, 1])

0.00     1.0
0.25     2.0
0.50     3.0
0.75     3.0
1.00    10.0
Name: Rooms, dtype: float64

In [ ]:
min = melbourne_data.Rooms.min()
max = melbourne_data.Rooms.max()
print(f'A su vez esto nos dice el valor minimo ({min}) y maximo ({max}) para dicha columna.')

A su vez esto nos dice el valor minimo (1) y maximo (10) para dicha columna.

Podemos interpretar esto como:
- El 25% de las casas tienen 2 habitaciones o menos
- El 50% de las casas tienen 3 habitaciones o menos
- El 75% de las casas tienen 3 habitaciones o menos
- El minimo de habitaciones que tienen las casas es 1 habitaciones (kinda obvious)
- El máximo de habitaciones que tienen las casas es 10.

Otro Ejemplo, con la columna Price:

In [ ]:
melbourne_data["Price"].quantile([0, .25, .5, .75, 1]) #Tambien se puede escribir asi

0.00      85000.0
0.25     650000.0
0.50     903000.0
0.75    1330000.0
1.00    9000000.0
Name: Price, dtype: float64

Podemos interpretar esto como:
- El 25% de las casas valen $650,000 (o menos).

- El 50% de las casas valen $903,000 (o menos).

- El 75% de las casas valen $1.330,000 (o menos).

- La casa con menor precio del dataset vale: $85,000.

- La casa con mayor precio del dataset vale: $9.000,000.

In [ ]:
from kagglehub import KaggleDatasetAdapter

In [ ]:
#Importando Iowa Houses Dataset
path =  "train.csv"
home_data = kagglehub.dataset_load(KaggleDatasetAdapter.PANDAS,"dansbecker/home-data-for-ml-course", path)

Using Colab cache for faster access to the 'home-data-for-ml-course' dataset.

In [ ]:
#Reviewing the data
home_data.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [ ]:
#What is the average lot size (rounded to nearest integer)
avg_lot_size = home_data.LotArea.mean().round()
print(f"average lot size: {avg_lot_size} m^2")
# As of today, how old is the newest home (current year - the date in which it was built)
newest_home_sold = 2026 - home_data.YearBuilt.max()
print(f"The most recent sold house was {newest_home_sold} years ago")

average lot size: 10517.0 m^2
The most recent sold house was 16 years ago